apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: {{ .Values.frontend.replicaCount }}
  selector:
    matchLabels:
        app: guestbook
        tier: frontend
  template:
    metadata:
      labels:
        app: guestbook
        tier: frontend
    spec:
      containers:
      - name: php-redis
        image: "{{ .Values.frontend.image.name }}:{{ .Values.frontend.image.tag }}"
        env:
        - name: GET_HOSTS_FROM
          value: "dns"
        ports:
        - containerPort: {{ .Values.frontend.containerPort }}
        resources:
{{ toYaml .Values.redisMaster.resources | indent 12 }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.redisMaster.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.redisMaster.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}

