apiVersion: v1
kind: Service
metadata:
  name: {{ template "guestbook.fullname" . }}-frontend
  labels:
    app: {{ template "guestbook.name" . }}
    tier: frontend
spec:
  type: LoadBalancer
  ports:
    - port: 80
  selector:
    app: {{ template "guestbook.name" . }}
    tier: frontend
