apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: frontend-ingress
  annotations:
    kubernetes.io/ingress.global-static-ip-name: {{ .Values.frontend.ingress.staticIpName }}
  labels:
    app: guestbook
    tier: frontend
spec:
  backend:
    serviceName: frontend
    servicePort: {{ .Values.frontend.service.port }}
