apiVersion: v1
kind: Service
metadata:
  name: {{ template "guestbook.fullname" . }}-redis-master
  labels:
    app: {{ template "guestbook.name" . }}-redis
    role: master
    tier: backend
spec:
  ports:
    - port: 6379
      targetPort: 6379
  selector:
    app: {{ template "guestbook.name" . }}-redis
    role: master
    tier: backend
 
