apiVersion: v1
kind: Service
metadata:
  name: {{ template "guestbook.fullname" . }}-redis-slave
  labels:
    app: {{ template "guestbook.name" . }}-redis
    role: slave
    tier: backend
    chart: {{ template "guestbook.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  ports:
    - port: 6379
  selector:
    app: {{ template "guestbook.name" . }}-redis
    release: {{ .Release.Name }}
    role: slave
    tier: backend
