apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ template "guestbook.fullname" . }}-redis-master
spec:
  replicas: {{ .Values.redisMaster.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "guestbook.name" . }}-redis
      role: master
      tier: backend
  template:
    metadata:
      labels:
        app: {{ template "guestbook.name" . }}-redis
        role: master
        tier: backend
    spec:
      containers:
        - name: {{ .Chart.Name }}-redis-master
          image: "{{ .Values.redisMaster.image.repository }}:{{ .Values.redisMaster.image.tag }}"
          imagePullPolicy: {{ .Values.redisMaster.image.pullPolicy }}
          ports:
            - containerPort: 6379
          #livenessProbe:
          #  httpGet:
          #    path: /
          #    port: http
          #readinessProbe:
          #  httpGet:
          #    path: /
          #    port: http
          resources:
{{ toYaml .Values.redisMaster.resources | indent 12 }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.redisMaster.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.redisMaster.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
