apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ template "guestbook.fullname" . }}-redis-slave
  labels:
    app: {{ template "guestbook.name" . }}
    chart: {{ template "guestbook.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.redisSlave.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "guestbook.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "guestbook.name" . }}
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}-redis-master
          image: "{{ .Values.redisSlave.image.repository }}:{{ .Values.redisSlave.image.tag }}"
          imagePullPolicy: {{ .Values.redisSlave.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
{{ toYaml .Values.redisSlave.resources | indent 12 }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.redisSlave.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.redisSlave.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
