apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-follower
  labels:
    app: redis
    role: follower
    tier: backend
spec:
  replicas: {{ .Values.redisSlave.replicaCount }}
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
        role: follower
        tier: backend
    spec:
      containers:
      - name: follower
        image: "{{ .Values.redisSlave.image.name }}:{{ .Values.redisSlave.image.tag }}"
        ports:
        - containerPort: 6379
        resources:
{{ toYaml .Values.redisMaster.resources | indent 12 }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.redisMaster.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.redisMaster.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}

        
        
