apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-leader
  labels:
    app: redis
    role: leader
    tier: backend
spec:
  replicas: {{ .Values.redisMaster.replicaCount }}
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
        role: leader
        tier: backend
    spec:
      containers:
      - name: leader
        image: "{{ .Values.redisMaster.image.name }}:{{ .Values.redisMaster.image.tag }}"
        ports:
        - containerPort: 6379
        resources:
{{ toYaml .Values.redisMaster.resources | indent 12 }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.redisMaster.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.redisMaster.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}

        
        
