apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ template "guestbook.fullname" . }}-redis-slave
spec:
  selector:
    matchLabels:
      app: {{ template "guestbook.name" . }}-redis
      role: slave
      tier: backend
  replicas: {{ .Values.redisSlave.replicaCount }}
  template:
    metadata:
      labels:
        app: {{ template "guestbook.name" . }}-redis
        role: slave
        tier: backend
    spec:
      containers:
        - name: {{ .Chart.Name }}-redis-slave
          image: "{{ .Values.redisSlave.image.repository }}:{{ .Values.redisSlave.image.tag }}"
          imagePullPolicy: {{ .Values.redisSlave.image.pullPolicy }}
          env:
            - name: GET_HOSTS_FROM
              value: dns
          ports:
            - containerPort: 6379
          #livenessProbe:
          #  httpGet:
          #    path: /
          #    port: http
          #readinessProbe:
          #  httpGet:
          #    path: /
          #    port: http
          resources:
{{ toYaml .Values.redisSlave.resources | indent 12 }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.redisSlave.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.redisSlave.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
